# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss
arch:
    epochs: 20
model:
    params:
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
        keypoint_net_type: "KeypointNet"
    checkpoint_path: '../../../scratch/rueeggth/kp2d'

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'default'
        fov: 60
        r_min: 0.1
        r_max: 5.0
        patch_ratio: 0.8
        scaling_amplitude: 0.3
        max_angle_div: 4
        super_resolution: 1
        preprocessing_gradient: True
        add_row_noise: True
        add_normal_noise: False
        add_sparkle_noise: False
        add_artifact: True
        blur: True
        add_speckle_noise: False
        normalize: True
        amp: 70
        artifact_amp: 200
    train:
        path: '../../../scratch/rueeggth/dataset/SonarDataSets/Simulated'
        num_workers: 16
        batch_size: 4
    val:
        path: "../../../scratch/rueeggth/dataset/SonarDataSets/SimEval"


