# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss
arch:
    epochs: 50
model:
    params:
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
        debug: True
        keypoint_net_type: "KeypointResnet"
    checkpoint_path: '../../../scratch/rueeggth/kp2dsonar'

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'sonar_sim'
        fov: 60
        r_min: 0.1
        r_max: 5.0
        patch_ratio: 0.9
        scaling_amplitude: 0.2
        max_angle_div: 2
        super_resolution: 1
        preprocessing_gradient: False
        add_row_noise: False
        add_normal_noise: True
        add_sparkle_noise: False
        add_artifact: False
        blur: False
        add_speckle_noise: False
        normalize: True
        amp: 70
        artifact_amp: 200
    train:
        path: "D:/MachineLearning/SonarData/SonarDataSets/Simulated"
        num_workers: 8
        batch_size: 4
    val:
        path: "D:/MachineLearning/SonarData/SonarDataSets/SimEval"
