# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model: 
#    + IONet
#    + descriptor upsampling 
#    + cross-border keypoints
#    + descriptor loss

model:
    params:
        debug: True
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
        keypoint_net_type: 'KeypointMAX'

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'quantized_default'
        jittering: (0.5, 0.5, 0.2, 0.05)
        image_shape: (240, 320)
    train:
        path: "D:/MachineLearning/Coco/train_debug"
    val:
        path: "D:/PycharmProjects/KP2D/data/datasets/kp2d/HPatches"

