# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model: 
#    + IONet
#    + descriptor upsampling 
#    + cross-border keypoints
#    + descriptor loss

arch:
    epochs: 10

model:
    params:
        debug: False
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
    checkpoint_path: '../../../scratch/rueeggth/kp2dsonar'

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'default'
        jittering: (0.5, 0.5, 0.2, 0.05)
    train:
        path: '../../../scratch/rueeggth/dataset/coco/train2017'
        batch_size: 4
        num_workers: 16
    val:
        path: "../../../scratch/rueeggth/dataset/HPatches"

