model:
    params:
        debug: True

datasets:
    train:
        path: "D:/MachineLearning/SonarData/SonarDataSets/Simulated"
        num_workers: 0
        batch_size: 3

    val:
        path: "D:/PycharmProjects/KP2D/data/datasets/kp2d/HPatches"