# Copyright 2020 Toyota Research Institute.  All rights reserved.

# Config for training the v4 model:
#    + IONet
#    + descriptor upsampling
#    + cross-border keypoints
#    + descriptor loss
device: "cpu"

model:
    params:
        debug: True
        device: cpu
        use_color: True
        with_io: True
        do_upsample: True
        do_cross: True
        descriptor_loss: True
        keypoint_net_type: 'KeypointMAX'

wandb:
    dry_run: True
    project: ""
datasets:
    augmentation:
        mode: 'sonar_sim'
        fov: 60
        r_min: 0.1
        r_max: 5.0
        patch_ratio: 0.7
        scaling_amplitude: 0.5
        max_angle_div: 4
        super_resolution: 2
        preprocessing_gradient: True
        add_row_noise: True
        add_normal_noise: False
        add_sparkle_noise: True
        add_artifact: True
        blur: True
        add_speckle_noise: False
        normalize: False
    train:
        path: "/home/thomas/Downloads/SonarDataSets/Simulated"
        num_workers: 0
        batch_size: 2

    val:
        path: "/home/thomas/Downloads/SonarDataSets/Simulated"

